[package]
name = "image-processing-experiments"
version = "1.0.0"
authors = ["Tobias Watzek <spitzfaust@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"

[dependencies.imageproc]
version = "0.18.0"
features = ["display-window"]

